# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: metric
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:

          token: ${{ secrets.SECRET_FUCKYOU }}

          user: berlintay
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Halifax
          config_twemoji: yes
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_pinned: 3
          plugin_stars: yes
          plugin_stars_limit: 4
          repositories_skipped: berlintay
